// <auto-generated />
namespace HP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RenameColumnPlayer_NumberInTableNHLPlayer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameColumnPlayer_NumberInTableNHLPlayer));
        
        string IMigrationMetadata.Id
        {
            get { return "201510060629470_RenameColumnPlayer_NumberInTableNHLPlayer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
